services:
  # Backend Servisi (Docker)
  - type: web
    name: watch-my-back-backend
    env: docker
    dockerContext: backend
    plan: free
    envVars:
      - key: PORT
        value: 3001
      - key: API_SECRET
        generateValue: true

  # Frontend Servisi (Docker)
  - type: web
    name: watch-my-back-frontend
    env: docker
    dockerContext: frontend
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: BACKEND_URL
        fromService:
          type: web
          name: watch-my-back-backend
          property: url
      - key: API_SECRET
        fromService:
          type: web
          name: watch-my-back-backend
          envVarKey: API_SECRET
